import { day1Challenge1, day1Challenge2 } from "./day1/day1";
import { day2Challenge1, day2Challenge2 } from "./day2/day2";
import { day3Challenge1, day3Challenge2 } from "./day3/day3";
import { day4Challenge1, day4Challenge2 } from "./day4/day4";
import { day5Challenge1, day5Challenge2 } from "./day5/day5";
import { day6Challenge1, day6Challenge2 } from "./day6/day6";

day1Challenge1();
day1Challenge2();
console.log();
day2Challenge1();
day2Challenge2();
console.log();
day3Challenge1();
day3Challenge2();
console.log();
day4Challenge1();
day4Challenge2();
console.log();
day5Challenge1();
day5Challenge2();
console.log();
day6Challenge1();
day6Challenge2();