import { day1Challenge1, day1Challenge2 } from "./day1/day1";
import { day2Challenge1, day2Challenge2 } from "./day2/day2";
import { day3Challenge1, day3Challenge2 } from "./day3/day3";
import { day4Challenge1, day4Challenge2 } from "./day4/day4";
import { day5Challenge1, day5Challenge2 } from "./day5/day5";
import { day6Challenge1, day6Challenge2 } from "./day6/day6";
import { day7Challenge1, day7Challenge2 } from "./day7/day7";
import { day8Challenge1, day8Challenge2 } from "./day8/day8";
import { day9Challenge1, day9Challenge2 } from "./day9/day9";
import { day10Challenge1, day10Challenge2 } from "./day10/day10";
import { day11Challenge1, day11Challenge2 } from "./day11/day11";

day1Challenge1();
day1Challenge2();
console.log();
day2Challenge1();
day2Challenge2();
console.log();
day3Challenge1();
day3Challenge2();
console.log();
day4Challenge1();
day4Challenge2();
console.log();
day5Challenge1();
day5Challenge2();
console.log();
day6Challenge1();
day6Challenge2();
console.log();
day7Challenge1();
day7Challenge2();
console.log();
day8Challenge1();
day8Challenge2();
console.log();
day9Challenge1();
day9Challenge2();
console.log();
day10Challenge1();
day10Challenge2();
console.log();
day11Challenge1();
day11Challenge2();